[phases.setup]
nixPkgs = ["...", "pango", "cairo", "gdk-pixbuf", "libffi", "fontconfig", "shared-mime-info"]
nixLibs = ["pango", "cairo", "gdk-pixbuf", "glib", "harfbuzz", "fontconfig", "freetype", "libffi"]
